import {
	Button,
	Card,
	Row,
	Col,
	Tag,
	Form,
	Input,
	Affix,
	Anchor,
	AutoComplete,
	Alert,
	Avatar,
	BackTop,
	Badge,
	Breadcrumb,
	Calendar,
	Collapse,
	Comment,
	Carousel,
	Cascader,
	Checkbox,
	ConfigProvider,
	DatePicker,
	Divider,
	Dropdown,
	Empty,
	InputNumber,
	Layout,
	List,
	Space,
	Menu,
	Mentions,
	Modal,
	Pagination,
	Popconfirm,
	Popover,
	Progress,
	Radio,
	Rate,
	Select,
	Slider,
	Spin,
	Statistic,
	Steps,
	Switch,
	Table,
	Transfer,
	Tree,
	TreeSelect,
	Tabs,
	TimePicker,
	Timeline,
	Tooltip,
	Upload,
	Drawer,
	Skeleton,
	Result,
	Descriptions,
	PageHeader,
} from 'ant-design-vue';
import { createApp } from 'vue';

/**
 * @description 手动注册 antd-vue 组件,达到按需加载目的
 * @description Automatically register components under Button, such as Button.Group
 * @param {ReturnType<typeof createApp>} app 整个应用的实例
 * @returns void
 */
export default function loadComponent(app: ReturnType<typeof createApp>) {
	app.use(Button);
	app.use(Card);
	app.use(Row);
	app.use(Col);
	app.use(Tag);
	app.use(Form);
	app.use(Input);
	app.use(Affix);
	app.use(Anchor);
	app.use(AutoComplete);
	app.use(Alert);
	app.use(Avatar);
	app.use(BackTop);
	app.use(Badge);
	app.use(Breadcrumb);
	app.use(Calendar);
	app.use(Collapse);
	app.use(Comment);
	app.use(Carousel);
	app.use(Cascader);
	app.use(Checkbox);
	app.use(ConfigProvider);
	app.use(DatePicker);
	app.use(Divider);
	app.use(Dropdown);
	app.use(Empty);
	app.use(InputNumber);
	app.use(Layout);
	app.use(List);
	app.use(Space);
	app.use(Menu);
	app.use(Mentions);
	app.use(Modal);
	app.use(Pagination);
	app.use(Popconfirm);
	app.use(Popover);
	app.use(Progress);
	app.use(Radio);
	app.use(Rate);
	app.use(Select);
	app.use(Slider);
	app.use(Spin);
	app.use(Statistic);
	app.use(Steps);
	app.use(Switch);
	app.use(Table);
	app.use(Transfer);
	app.use(Tree);
	app.use(TreeSelect);
	app.use(Tabs);
	app.use(TimePicker);
	app.use(Timeline);
	app.use(Tooltip);
	app.use(Upload);
	app.use(Drawer);
	app.use(Skeleton);
	app.use(Result);
	app.use(Descriptions);
	app.use(PageHeader);
}
